language: node_js
node_js: '7'
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: c0C+ZBxGkerPmAiRid/i0HtHhIkKrXpbvrvBpDmqJpoKcc3isdD8wsuueVIAFXa+4s5wZH7w314LCBJTA3MPdhN6wHwYJH22szFq0HHe719yBy1K9RT68YLAjGs9usxf57l9J98VIfdD8vyLQ1gueZXuojNygyISHU8Kb9XDnVt+ADE12MGY4QjXj7gejoLrpTli8LB7Muk7Wl7zMGN6o8X5xWlCCC24VP8d4c7uFQ17UvvdD4Jsuu8FKiHRQvkA7h09O5cjdorqqJLNLM18dHZl1rxPOQTWFcS/m2Vrn0je2ItE9DjaH1mLiHBhOTLk+NalHSLhJA1ZXh/K0RodTGPE3AcwVLOU3pjADcXlerX8Khwb/3VEm5QkSbXOVLH/EzjEgn34LKj6mVD2e5XJtyxeHEyx3yh24D4v65te5SMFj1n6EI4KO/mq0Q06uwn3ZH5zXpC8itf0DDVHDXX/kyrmpEnH7BO+e3a080Pqx5lHWHRbXZv/MRkOTfhy+4NcvFeMlJCh+mQ65JVnBvLtwK4dbjwVpuxkvf5DTzpzR0LJJ/IpbpOxCsxnHZbg/9pRZ1xljJCIcyb73pM6FqY55XiQ790tQ1ykL+v34DvNW9VYI6MqdjPW888KqDTeNO1PYmMFwBjJjdb4gKgT1gLPN5pdEIPrH7WXPkhQrjj7oF4=
  app: dinnerplans-condericson
  on:
    repo: condericson/mealprepapp
